"""
Signal registry. Each module exports a compute(daily, lob=None) -> pd.DataFrame function.
Returns a (trade_day_id x asset_id) DataFrame of cross-sectionally z-scored signal values.
"""

from signals import (
    short_term_reversal,
    lob_imbalance,
    price_to_vwap,
    volume_reversal,
    ofi_matched_filter,
    ofi_ou,
    alpha191_046,
    alpha191_071,
    composite_daily,
    composite_full,
    low_vol,
    stable_turnover_momentum,
    vol_managed,
    inv_var_vol,
    cluster_low_vol,
    hmm_regime_vol,
    vol_managed_120d,
    vol_managed_v2,
    low_beta,
    return_consistency,
    rolling_sharpe,
    trend_filtered_low_vol,
    quality_composite,
    erc_vol_managed,
    trend_vol_v2,
    trend_vol_v3,
)

REGISTRY = {
    "short_term_reversal": short_term_reversal,
    "lob_imbalance": lob_imbalance,
    "price_to_vwap": price_to_vwap,
    "volume_reversal": volume_reversal,
    "ofi_matched_filter": ofi_matched_filter,
    "ofi_ou": ofi_ou,
    "alpha191_046": alpha191_046,
    "alpha191_071": alpha191_071,
    "composite_daily": composite_daily,
    "composite_full": composite_full,
    "low_vol": low_vol,
    "stable_turnover_momentum": stable_turnover_momentum,
    "vol_managed": vol_managed,
    "inv_var_vol": inv_var_vol,
    "cluster_low_vol": cluster_low_vol,
    "hmm_regime_vol": hmm_regime_vol,
    "vol_managed_120d": vol_managed_120d,
    "vol_managed_v2": vol_managed_v2,
    "low_beta": low_beta,
    "return_consistency": return_consistency,
    "rolling_sharpe": rolling_sharpe,
    "trend_filtered_low_vol": trend_filtered_low_vol,
    "quality_composite": quality_composite,
    "erc_vol_managed": erc_vol_managed,
    "trend_vol_v2": trend_vol_v2,
    "trend_vol_v3": trend_vol_v3,
}
