"""
Pre-registered evaluation of trend_vol_v6.

See wiki/decisions/001-kill-criteria-trend-vol-v6.md for the protocol.

Partitions IS data into:
  - Tuning: D001-D400
  - Held-out: D401-D484

Signals are computed on FULL D001-D484 daily (so lookback windows are
populated at the start of the held-out window). Backtest execution is
restricted to each partition.

Outputs:
  wiki/results/2026-05-20-trend-vol-v6-validation.md
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from eval.backtest import run_backtest  # noqa: E402
from eval.layers import compute as compute_layers  # noqa: E402
from signals import trend_vol_v4, trend_vol_v6  # noqa: E402


CUTOFF = "D400"  # tuning ends here (inclusive); validation starts at D401


def partition(daily: pd.DataFrame, cutoff: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    tune = daily[daily["trade_day_id"] <= cutoff]
    val = daily[daily["trade_day_id"] > cutoff]
    return tune, val


def fmt_row(label: str, res: dict, m) -> str:
    return (
        f"| {label} | {res['cagr']*100:+.2f}% | {res['sharpe']:.3f} | "
        f"{res['mdd']*100:.2f}% | {m.calmar:.2f} | {m.ulcer_index:.2f} | "
        f"{m.martin_ratio:.2f} | {m.kurt_excess:+.2f} | {res['score']:.4f} |"
    )


def verdict(d_tune: float, d_held: float, ulcer_v6: float, ulcer_v4: float) -> str:
    """Decision per wiki/decisions/001-kill-criteria-trend-vol-v6.md."""
    if d_tune <= 0.01:
        return "REJECT — tuning ΔScore ≤ +0.01, no signal"
    if d_held > 0.05:
        return "INVESTIGATE — held-out delta suspiciously large (>+0.05)"
    if d_held <= 0:
        return "SHELVE — tuning gain did not survive held-out"
    if ulcer_v6 - ulcer_v4 > 0.5:
        return "SHELVE — ulcer-degradation flag (>+0.5)"
    return "PROMOTE — tuning ΔScore > +0.01 AND held-out ΔScore > 0"


def main() -> None:
    daily_full = pd.read_parquet(ROOT / "data" / "daily_data_in_sample.parquet")
    print(f"Loaded daily data: {len(daily_full):,} rows, "
          f"{daily_full['trade_day_id'].nunique()} days", flush=True)

    # Signals computed on FULL data so lookbacks span the cutoff
    print("Computing signals on full D001–D484...", flush=True)
    sig4 = trend_vol_v4.compute(daily_full)
    w4 = trend_vol_v4.compute_weights(daily_full)
    sig6 = trend_vol_v6.compute(daily_full)
    w6 = trend_vol_v6.compute_weights(daily_full)

    daily_tune, daily_val = partition(daily_full, CUTOFF)
    print(f"  tuning days:    {daily_tune['trade_day_id'].nunique()}", flush=True)
    print(f"  held-out days:  {daily_val['trade_day_id'].nunique()}", flush=True)

    results: dict[str, dict] = {}
    metrics: dict[str, object] = {}

    for tag, dly in [("tune", daily_tune), ("val", daily_val)]:
        print(f"\n[{tag}] running v4...", flush=True)
        r4 = run_backtest(dly, sig4, sell_mode="open", n_stocks=20, weights=w4)
        m4 = compute_layers(r4["portfolio_value"])
        results[f"v4_{tag}"] = r4
        metrics[f"v4_{tag}"] = m4

        print(f"[{tag}] running v6...", flush=True)
        r6 = run_backtest(dly, sig6, sell_mode="open", n_stocks=20, weights=w6)
        m6 = compute_layers(r6["portfolio_value"])
        results[f"v6_{tag}"] = r6
        metrics[f"v6_{tag}"] = m6

    # Decision deltas (Score basis)
    d_tune = results["v6_tune"]["score"] - results["v4_tune"]["score"]
    d_held = results["v6_val"]["score"] - results["v4_val"]["score"]
    v = verdict(
        d_tune, d_held,
        metrics["v6_val"].ulcer_index, metrics["v4_val"].ulcer_index,
    )

    # Markdown report
    lines: list[str] = [
        "# trend_vol_v6 — Pre-Registered Validation",
        "",
        f"_Generated by `scripts/validate_trend_vol_v6.py` on 2026-05-20._",
        f"_Protocol: see `wiki/decisions/001-kill-criteria-trend-vol-v6.md`._",
        "",
        "## Tuning window (D001–D400)",
        "",
        "| Signal | CAGR | Sharpe | MDD | Calmar | Ulcer | Martin | Kurt | Score |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        fmt_row("trend_vol_v4", results["v4_tune"], metrics["v4_tune"]),
        fmt_row("trend_vol_v6", results["v6_tune"], metrics["v6_tune"]),
        "",
        f"ΔScore (v6 − v4) = **{d_tune:+.4f}**",
        "",
        "## Held-out window (D401–D484)",
        "",
        "| Signal | CAGR | Sharpe | MDD | Calmar | Ulcer | Martin | Kurt | Score |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        fmt_row("trend_vol_v4", results["v4_val"], metrics["v4_val"]),
        fmt_row("trend_vol_v6", results["v6_val"], metrics["v6_val"]),
        "",
        f"ΔScore (v6 − v4) = **{d_held:+.4f}**",
        "",
        "## Verdict",
        "",
        f"**{v}**",
        "",
        "## Notes",
        "",
        f"- Tuning days: {results['v4_tune']['n_days']}; "
        f"held-out days: {results['v4_val']['n_days']}.",
        "- Sell mode = open, N = 20 for both signals (v6 native, v4 native).",
        "- Signals were computed on full D001–D484 daily data so 35d trend "
        "and 60d vol lookbacks are populated at the held-out start.",
    ]

    out = ROOT / "wiki" / "results" / "2026-05-20-trend-vol-v6-validation.md"
    out.write_text("\n".join(lines) + "\n")

    print("\n" + "=" * 70)
    print(f"\nTuning ΔScore   = {d_tune:+.4f}")
    print(f"Held-out ΔScore = {d_held:+.4f}")
    print(f"\nVerdict: {v}")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
