"""
Pre-registered evaluation of `clustering_reversal`.

Protocol: wiki/decisions/002-kill-criteria-clustering-reversal.md
Gates:
  1. Standalone viability — tuning CAGR > 0 AND held-out CAGR > 0
  2. Orthogonality — pairwise corr vs trend_vol_v4 < 0.85
  3. Portfolio additivity — MDB-eq, MDB-rp, MDB-mv all > 0 vs {v4}

Writes wiki/results/2026-05-20-clustering-reversal-validation.md.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from eval.backtest import run_backtest  # noqa: E402
from eval.correlation_mdb import (  # noqa: E402
    correlation_matrix,
    marginal_diversification_benefit,
    returns_matrix,
)
from eval.layers import compute as compute_layers  # noqa: E402
from signals import clustering_reversal, trend_vol_v4  # noqa: E402


CUTOFF = "D400"


def partition(daily: pd.DataFrame, cutoff: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    tune = daily[daily["trade_day_id"] <= cutoff]
    val = daily[daily["trade_day_id"] > cutoff]
    return tune, val


def fmt_row(label: str, res: dict, m) -> str:
    return (
        f"| {label} | {res['cagr']*100:+.2f}% | {res['sharpe']:.3f} | "
        f"{res['mdd']*100:.2f}% | {m.calmar:.2f} | {m.ulcer_index:.2f} | "
        f"{m.martin_ratio:.2f} | {m.kurt_excess:+.2f} | {res['score']:.4f} |"
    )


def main() -> None:
    daily_full = pd.read_parquet(ROOT / "data" / "daily_data_in_sample.parquet")
    print(f"Loaded daily data: {len(daily_full):,} rows, "
          f"{daily_full['trade_day_id'].nunique()} days", flush=True)

    print("Computing trend_vol_v4 signal...", flush=True)
    sig4 = trend_vol_v4.compute(daily_full)
    w4 = trend_vol_v4.compute_weights(daily_full)

    print("Computing clustering_reversal signal...", flush=True)
    sig_cr = clustering_reversal.compute(daily_full)

    daily_tune, daily_val = partition(daily_full, CUTOFF)
    print(f"  tuning days:    {daily_tune['trade_day_id'].nunique()}", flush=True)
    print(f"  held-out days:  {daily_val['trade_day_id'].nunique()}", flush=True)

    results: dict[str, dict] = {}
    metrics: dict[str, object] = {}

    for tag, dly in [("tune", daily_tune), ("val", daily_val), ("full", daily_full)]:
        print(f"\n[{tag}] running v4...", flush=True)
        r4 = run_backtest(dly, sig4, sell_mode="open", n_stocks=20, weights=w4)
        m4 = compute_layers(r4["portfolio_value"])
        results[f"v4_{tag}"] = r4
        metrics[f"v4_{tag}"] = m4

        print(f"[{tag}] running clustering_reversal...", flush=True)
        r_cr = run_backtest(dly, sig_cr, sell_mode="open", n_stocks=20)
        m_cr = compute_layers(r_cr["portfolio_value"])
        results[f"cr_{tag}"] = r_cr
        metrics[f"cr_{tag}"] = m_cr

    # ── Gate 1 — standalone viability ─────────────────────────────────────────
    cagr_tune = results["cr_tune"]["cagr"]
    cagr_val = results["cr_val"]["cagr"]
    g1_pass = cagr_tune > 0 and cagr_val > 0

    # ── Gate 2 — orthogonality (correlation vs v4, full IS) ───────────────────
    wallets_full = {
        "trend_vol_v4": results["v4_full"]["portfolio_value"],
        "clustering_reversal": results["cr_full"]["portfolio_value"],
    }
    rmat = returns_matrix(wallets_full)
    corr_full = correlation_matrix(rmat).loc["trend_vol_v4", "clustering_reversal"]
    g2_pass = corr_full < 0.85

    # ── Gate 3 — portfolio additivity (MDB vs {v4}, full IS) ──────────────────
    book = ["trend_vol_v4"]
    mdb_eq = marginal_diversification_benefit(rmat, book, "clustering_reversal", "eq")
    mdb_rp = marginal_diversification_benefit(rmat, book, "clustering_reversal", "rp")
    mdb_mv = marginal_diversification_benefit(rmat, book, "clustering_reversal", "mv")
    g3_pass = mdb_eq > 0 and mdb_rp > 0 and mdb_mv > 0

    if cagr_tune > 0.12 and cagr_val > 0.12:
        verdict = "INVESTIGATE — suspiciously high standalone CAGR (>+12%); check execution-IC before promoting"
    elif g1_pass and g2_pass and g3_pass:
        verdict = "PROMOTE — all three gates passed"
    else:
        fails = []
        if not g1_pass:
            fails.append("Gate 1 (standalone viability)")
        if not g2_pass:
            fails.append("Gate 2 (orthogonality)")
        if not g3_pass:
            fails.append("Gate 3 (portfolio additivity)")
        verdict = f"SHELVE — failed: {', '.join(fails)}"

    # ── Report ────────────────────────────────────────────────────────────────
    lines = [
        "# clustering_reversal — Pre-Registered Validation",
        "",
        f"_Generated by `scripts/validate_clustering_reversal.py` on 2026-05-20._",
        f"_Protocol: see `wiki/decisions/002-kill-criteria-clustering-reversal.md`._",
        "",
        "## Standalone backtests",
        "",
        "### Tuning window (D001–D400)",
        "",
        "| Signal | CAGR | Sharpe | MDD | Calmar | Ulcer | Martin | Kurt | Score |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        fmt_row("trend_vol_v4", results["v4_tune"], metrics["v4_tune"]),
        fmt_row("clustering_reversal", results["cr_tune"], metrics["cr_tune"]),
        "",
        "### Held-out window (D401–D484)",
        "",
        "| Signal | CAGR | Sharpe | MDD | Calmar | Ulcer | Martin | Kurt | Score |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        fmt_row("trend_vol_v4", results["v4_val"], metrics["v4_val"]),
        fmt_row("clustering_reversal", results["cr_val"], metrics["cr_val"]),
        "",
        "### Full IS (D001–D484)",
        "",
        "| Signal | CAGR | Sharpe | MDD | Calmar | Ulcer | Martin | Kurt | Score |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        fmt_row("trend_vol_v4", results["v4_full"], metrics["v4_full"]),
        fmt_row("clustering_reversal", results["cr_full"], metrics["cr_full"]),
        "",
        "## Pre-registered gates",
        "",
        "| Gate | Criterion | Value | Pass? |",
        "|---|---|---:|:---:|",
        f"| 1 | Tuning CAGR > 0 | {cagr_tune*100:+.2f}% | "
        f"{'✓' if cagr_tune > 0 else '✗'} |",
        f"| 1 | Held-out CAGR > 0 | {cagr_val*100:+.2f}% | "
        f"{'✓' if cagr_val > 0 else '✗'} |",
        f"| 2 | corr vs v4 < 0.85 | {corr_full:.3f} | "
        f"{'✓' if g2_pass else '✗'} |",
        f"| 3 | MDB-eq vs {{v4}} > 0 | {mdb_eq:+.4f} | "
        f"{'✓' if mdb_eq > 0 else '✗'} |",
        f"| 3 | MDB-rp vs {{v4}} > 0 | {mdb_rp:+.4f} | "
        f"{'✓' if mdb_rp > 0 else '✗'} |",
        f"| 3 | MDB-mv vs {{v4}} > 0 | {mdb_mv:+.4f} | "
        f"{'✓' if mdb_mv > 0 else '✗'} |",
        "",
        "## Verdict",
        "",
        f"**{verdict}**",
    ]

    out = ROOT / "wiki" / "results" / "2026-05-20-clustering-reversal-validation.md"
    out.write_text("\n".join(lines) + "\n")

    print("\n" + "=" * 70)
    print(f"\nGate 1 (tune CAGR > 0)        : {cagr_tune*100:+.2f}%  "
          f"{'PASS' if cagr_tune > 0 else 'FAIL'}")
    print(f"Gate 1 (held-out CAGR > 0)    : {cagr_val*100:+.2f}%  "
          f"{'PASS' if cagr_val > 0 else 'FAIL'}")
    print(f"Gate 2 (corr vs v4 < 0.85)    : {corr_full:.3f}  "
          f"{'PASS' if g2_pass else 'FAIL'}")
    print(f"Gate 3 (MDB-eq > 0)           : {mdb_eq:+.4f}  "
          f"{'PASS' if mdb_eq > 0 else 'FAIL'}")
    print(f"Gate 3 (MDB-rp > 0)           : {mdb_rp:+.4f}  "
          f"{'PASS' if mdb_rp > 0 else 'FAIL'}")
    print(f"Gate 3 (MDB-mv > 0)           : {mdb_mv:+.4f}  "
          f"{'PASS' if mdb_mv > 0 else 'FAIL'}")
    print(f"\nVerdict: {verdict}")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
